/**
 * This code was generated by Builder.io.
 */
import React from "react";

const donHang: React.FC = () => {
  return (
    <main className="flex flex-col ml-5 w-9/12 max-md:ml-0 max-md:w-full">
      <div className="box-border relative shrink-0 mt-5 h-auto">
        <p>
          <span className="text-red-700">Enter some aaaaaaa22</span>
        </p>
      </div>
    </main>
  );
};

export default donHang;
