/**
 * This code was generated by Builder.io.
 */
import React from 'react';

interface FooterLinkProps {
  href: string;
  text: string;
}

const FooterLink: React.FC<FooterLinkProps> = ({ href, text }) => (
  <a
    href={href}
    target="_blank"
    rel="noopener noreferrer"
    className="box-border relative shrink-0 h-auto text-sm text-left text-white cursor-pointer pointer-events-auto max-md:text-center"
  >
    <p>{text}</p>
  </a>
);

const Footer: React.FC = () => {
  return (
    <footer className="builder-footer box-border flex relative flex-col shrink-0 self-stretch px-5 pt-8 pb-10 w-screen text-white bg-blue-400 min-h-[383px] ml-[calc(50%_-_50vw)] max-sm:pt-5">
      <section className="builder-footer box-border flex relative flex-col grow shrink-0 self-stretch px-5 pt-8 pb-10 mx-auto w-full text-white bg-blue-400 max-w-[1200px] min-h-[383px] max-sm:pt-5">
        <div className="box-border flex relative flex-col shrink-0 mx-auto mt-5 w-full max-w-[600px]">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="box-border flex relative flex-col shrink-0 max-md:items-center">
                <div className="box-border flex relative flex-col shrink-0">
                  <h2 className="box-border relative shrink-0 h-auto text-base font-semibold text-left text-white">
                    Integrating Builder with your app
                  </h2>
                  <div className="box-border flex relative flex-col shrink-0 gap-2.5 pt-2.5 leading-relaxed">
                    <FooterLink href="https://www.builder.io/c/docs/how-builder-works-technical" text="How Builder Works" />
                    <FooterLink href="https://www.builder.io/c/docs/integrate-symbols" text="Integrate Symbols" />
                    <FooterLink href="https://www.builder.io/c/docs/integrate-cms-data" text="Using Builder CMS data" />
                    <FooterLink href="https://www.builder.io/c/docs/api-intro" text="Builder API" />
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="box-border flex relative flex-col shrink-0 max-md:items-center max-md:mt-7">
                <h2 className="box-border relative shrink-0 h-auto text-base font-semibold text-left text-white">
                  Learn the Builder Visual Editor
                </h2>
                <div className="box-border flex relative flex-col shrink-0 gap-2.5 pt-2.5">
                  <FooterLink href="https://www.builder.io/c/docs/how-builder-works" text="Builder Docs" />
                  <FooterLink href="https://www.builder.io/c/docs/custom-components-intro" text="Custom Components" />
                  <FooterLink href="https://www.builder.io/c/blueprints" text="Blueprints" />
                  <FooterLink href="https://forum.builder.io/" text="Forum" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </footer>
  );
};

export default Footer;