/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import SearchBar from './SearchBar';
import Navigation from './Navigation';

const Header: React.FC = () => {
  return (
    <header className="box-border flex overflow-hidden overflow-x-hidden overflow-y-hidden relative flex-col shrink-0 mt-px bg-white">
      <img loading="lazy" alt="WeCare logo" src="https://cdn.builder.io/api/v1/image/assets%2F72645f1c581446d9b326ff62153df84b%2F4cabc051b75443448a1a92bff409187c" className="box-border object-contain object-left overflow-hidden absolute top-px shrink-0 mr-0 aspect-square h-[77px] left-[33px] max-w-[148px] min-h-[20px] min-w-[20px] w-[67px]" />
      <div className="box-border flex relative flex-col shrink-0">
        <div className="flex flex-row">
          <h1 className="pb-3 pl-12 mt-3 mb-auto ml-14 text-4xl text-cyan-600 font-[bold]">
            WECARE
          </h1>
          <SearchBar />
        </div>
      </div>
      <Navigation />
    </header>
  );
};

export default Header;