/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const navigationItems = [
  { label: 'Trang Chủ', href: '#' },
  { label: 'Sản phẩm', href: '#' },
  { label: 'Về chúng tôi', href: '#' },
  { label: 'Tin tức', href: '#' },
  { label: 'Đơn hàng·', href: '#' },
  { label: 'Kho vận', href: '#' },
];

const Navigation: React.FC = () => {
  return (
    <nav className="flex gap-0 self-stretch my-auto max-md:justify-center">
      {navigationItems.map((item, index) => (
        <a key={index} href={item.href} className="pr-4 pl-5 my-auto text-cyan-600 no-underline">
          <h4>{item.label}</h4>
        </a>
      ))}
    </nav>
  );
};

export default Navigation;