/**
 * This code was generated by Builder.io.
 */
import React from "react";

const SearchBar: React.FC = () => {
  return (
    <form className="box-border flex absolute top-2 flex-col grow shrink-0 justify-center items-start self-center py-2 pr-16 pl-3.5 rounded-3xl bg-[white] h-[51px] left-[366px] max-w-[662px] shadow-[0_6px_10px_rgba(30,144,197,0.5)] w-[820px]">
      <label htmlFor="search-input" className="sr-only">
        Tìm kiếm và nhấn enter
      </label>
      <input
        id="search-input"
        type="text"
        placeholder="Tìm kiếm và nhấn enter"
        className="absolute top-2 left-3 grow px-4 py-2.5 ml-2.5 rounded-3xl rounded-tl-3xl border-[none] w-[333px]"
      />
      {/* <button
        type="submit"
        className="absolute py-2.5 pr-5 pl-9 bg-sky-500 rounded-none border-white cursor-pointer border-[none] h-[51px] left-[906px] text-[white] top-[7px] w-[116px]"
      >
        Search
      </button> */}
    </form>
  );
};

export default SearchBar;
