/**
 * This code was generated by Builder.io.
 */
import React from "react";

const sidebarButtons = [
  "Danh mục sản phẩm",
  "Đơn bán",
  "Đơn Mua",
  "Thông tin",
  "Vận tải",
];

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-2/12 max-md:ml-0 max-md:w-full">
      <div className="box-border flex relative flex-col shrink-0 p-0 mr-0 min-h-[auto]">
        {" "}
        {/* Giảm padding về 0 */}
        <section className="box-border flex relative flex-col grow shrink-0 self-stretch p-0 mx-auto w-full max-w-[900px] min-h-[auto]">
          {" "}
          {/* Giảm padding về 0 */}
          {sidebarButtons.map((text, index) => (
            <button
              key={index}
              className="box-border relative shrink-0 px-0 py-0 mt-5 text-center text-blue-500 rounded appearance-none cursor-pointer bg-neutral-200"
            >
              {" "}
              {/* Giảm padding về 0 */}
              {text}
            </button>
          ))}
        </section>
      </div>
    </aside>
  );
};

export default Sidebar;
