/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const sidebarButtons = [
  'Click me!',
  'Click me!',
  'Click me!',
  'Click me!',
  'Click me!',
  'Click me!',
  'Click me!',
  'Click me!',
];

const Sidebar: React.FC = () => {
  return (
    <aside className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
      <div className="box-border flex relative flex-col shrink-0 py-5 pr-5 pl-5 mr-0 min-h-[auto]">
        <section className="box-border flex relative flex-col grow shrink-0 self-stretch py-5 pr-5 pl-5 mx-auto w-full max-w-[1200px] min-h-[auto]">
          {sidebarButtons.map((text, index) => (
            <button
              key={index}
              className="box-border relative shrink-0 px-6 py-4 mt-5 text-center text-blue-500 rounded appearance-none cursor-pointer bg-neutral-200"
            >
              {text}
            </button>
          ))}
        </section>
      </div>
    </aside>
  );
};

export default Sidebar;